services:

  db:
    image: postgres:15
    container_name: pilamunga_db
    restart: always
    environment:
      POSTGRES_USER: Pilamunga_Carlos
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: micro_pilamunga_db
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U Pilamunga_Carlos -d micro_pilamunga_db -h localhost"]
      interval: 5s
      timeout: 3s
      retries: 20

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    container_name: pilamunga_client
    restart: always
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: Pilamunga_Carlos
      DB_PASSWORD: 1234
      DB_DATABASE: micro_pilamunga_db
      PORT: 3000
    depends_on:
      db:
        condition: service_healthy

  user_service:
    build:
      context: .
      dockerfile: user_service/Dockerfile
    container_name: pilamunga_user_service
    restart: always
    ports:
      - "3001:3001"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: Pilamunga_Carlos
      DB_PASSWORD: 1234
      DB_DATABASE: micro_pilamunga_db
      PORT: 3001
    depends_on:
      db:
        condition: service_healthy

  order_service:
    build:
      context: .
      dockerfile: order_service/Dockerfile
    container_name: pilamunga_order_service
    restart: always
    ports:
      - "3002:3002"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: Pilamunga_Carlos
      DB_PASSWORD: 1234
      DB_DATABASE: micro_pilamunga_db
      PORT: 3002
      USER_MICROSERVICE_URL: http://user_service:3001/api/users
      PRODUCT_MICROSERVICE_URL: http://client:3000/api/products
    depends_on:
      db:
        condition: service_healthy
      user_service:
        condition: service_started
      client:
        condition: service_started
